#!/usr/bin/expect
#./test | perl -ne 'print if $_ =~ /(SPAWN|LOGIN|WILCO|LOGOUT|SYS|LS|GET|PUT)/'
#log_user 0
for { set i 1 } {$i <= 100} { incr i } {

	spawn java -jar client.jar
	expect "quarac>"
	send "login\n"
	expect "Domain:"
	send "ece_linux\n"
	expect "Username:"
	send "teamA\n"
	expect "Password"
	send "teamA\n"
	#expect "LOGIN" { echo "LOGIN" }
	set timeout 6000 
	expect "quarac>" { send "ls\n" }
	expect "quarac>" { send "put testFiles/homer_odyssey.txt homer_odyssesy.txt\n" }
	expect "quarac>" { send "get homer_odyssey.txt homer_odyssesy.txt\n" }
	expect "quarac>" { send "exit\n"}
}
