#!/bin/bash
#
# ##Vinay Bharadwaj (vind.1989@gatech.edu)## Description: File service  
#
# Start the service 
DIR="$(pwd)"
NUM=$2
i=0
start() {
	echo $NUM > num_servers
        while(($i < $NUM)) 
	do
	j=$(($i+9090)) d=$(($i+20000))
	$DIR/server_file_test $j $d &
	i=$(($i+1))	
	done
	echo -n "File service started."
	echo 
	
}
# Restart the service TEST
stop() {
        pkill server	rm num_servers
        echo "File service stopped."
}
### main logic ###

case "$1" in
  start)
	if(($# < 2)); then 
	echo $"Usage: $0 {start [num_servers] | stop | restart | reload}"
        exit 1
	fi
        start 
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
